import { useSars } from "@/hooks/use-sars";
import { Sidebar } from "@/components/Sidebar";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { LoadingSpinner } from "@/components/LoadingSpinner";
import { FileText, Eye } from "lucide-react";
import { format } from "date-fns";
import { Link } from "wouter";

export default function SarsList() {
  const { data: sars, isLoading } = useSars();

  const getStatusColor = (status: string) => {
    switch (status) {
      case "published": return "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400";
      case "draft": return "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400";
      default: return "bg-gray-100 text-gray-800 dark:bg-gray-900/30 dark:text-gray-400";
    }
  };

  return (
    <div className="flex h-screen bg-background">
      <Sidebar />
      
      <main className="flex-1 overflow-auto">
        <div className="p-8 max-w-7xl mx-auto">
          <div className="mb-8">
            <h1 className="text-4xl font-bold text-foreground mb-2">
              Suspicious Activity Reports
            </h1>
            <p className="text-muted-foreground">
              View and manage AI-generated SAR narratives
            </p>
          </div>

          {isLoading ? (
            <div className="flex items-center justify-center h-64">
              <LoadingSpinner size="lg" />
            </div>
          ) : (
            <div className="space-y-4">
              {sars?.map((sar: any) => (
                <Card key={sar.id} className="p-6 hover:shadow-md transition-shadow">
                  <div className="flex items-start justify-between">
                    <div className="flex gap-4 flex-1">
                      <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center flex-shrink-0">
                        <FileText className="w-6 h-6 text-primary" />
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <h3 className="text-lg font-semibold text-foreground">
                            {sar.title}
                          </h3>
                          <Badge variant="outline" className={getStatusColor(sar.status)}>
                            {sar.status}
                          </Badge>
                        </div>
                        <div className="grid grid-cols-3 gap-4 text-sm">
                          <div>
                            <p className="text-muted-foreground">Version</p>
                            <p className="font-medium text-foreground">{sar.version}</p>
                          </div>
                          <div>
                            <p className="text-muted-foreground">Generated By</p>
                            <p className="font-medium text-foreground">{sar.generatedBy}</p>
                          </div>
                          <div>
                            <p className="text-muted-foreground">Created</p>
                            <p className="font-medium text-foreground">
                              {format(new Date(sar.createdAt), "PP")}
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <Link href={`/sars/${sar.id}`}>
                      <Button className="gap-2">
                        <Eye className="w-4 h-4" />
                        View Details
                      </Button>
                    </Link>
                  </div>
                </Card>
              ))}
              {(!sars || sars.length === 0) && (
                <div className="text-center py-12">
                  <p className="text-muted-foreground">No SARs generated yet</p>
                </div>
              )}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
